### ISSUE TITLE
Media breakpoints that reuse styles are not applied

### ISSUE THREAD

**Issue by RJWadley** [souporserious/restyle#23]
If multiple components share styles under the same breakpoint, restyle will reuse the selector. However, because of specificity rules the reused selector has lower priority that the base styles for that component.

[Reproduction in codesandbox](https://codesandbox.io/p/sandbox/restyle-basic-usage-forked-d3xttt)

For example:
```javascript
const A = styled("div", {
  background: "green",
  "@media (max-width: 600px)": {
    background: "yellow",
  },
});

const B = styled("div", {
  background: "orange",
  "@media (max-width: 600px)": {
    background: "yellow",
  },
});
```

spits out the following CSS:
```css
.l1t9gvek{background:green}
@media (max-width: 600px){.ln90kp8{background:yellow}}
.lc6uyq4{background:orange}
```

Although I haven't thought too hard about it yet, I would expect something a bit closer to this:
```css
.l1t9gvek{background:green}
@media (max-width: 600px){.ln90kp8{background:yellow}}
.lc6uyq4{background:orange}
@media (max-width: 600px){.ln90kp8{background:yellow}}
```
or, alternatively:
```css
.l1t9gvek{background:green}
.lc6uyq4{background:orange}
@media (max-width: 600px){.ln90kp8{background:yellow}}
``` 
this would notably flip the precedence which makes the media query more important. for the sake determinism it may also make sense to always render media queries last, regardless of the source order, to prevent this same issue from sometimes happening in reverse.
